package Elena.Uberly_backend.Enum;

public enum Tags {
    MEMES, SHORT_TRAVEL, LONG_TRAVEL, ADVENTURE, FULL_NATURE, CITY_EXPLORATION, TO_THE_BEACH, FEEDBACK, FUN, CHILL, EVENT,
    TRAVEL_GUIDE, QUICK_RIDE, TO_THE_MOUNTAINS
}
